# Generated by Django 4.2.5 on 2024-04-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_floor', models.IntegerField()),
                ('serviced_floors', models.CharField(max_length=100)),
                ('destination_floors', models.CharField(max_length=100)),
            ],
        ),
    ]
